// ABOUTME: Proves strict text renderers keep hostile markup inert and stop at bounds.
// ABOUTME: Synthetic hostile inputs assert escaping, subset drops, caps, and render time.

import { describe, expect, it } from "vitest";

import {
  buildTextDocument,
  buildViewerFallback,
  escapeHtml,
  renderDiffToHtml,
  renderJsonToHtml,
  renderLogToHtml,
  renderMarkdownToHtml,
  renderMermaidToSvg,
  VIEWER_MAX_MERMAID_EDGES,
  VIEWER_MAX_MERMAID_NODES,
} from "../src/renderers.js";

const HOSTILE_SCRIPT = `</script><script>alert(document.cookie)</script>`;
const HOSTILE_IMG = `<img src=x onerror=alert(1)>`;

// Structural allowlist: every raw tag in renderer output must be generated by
// the renderer with quoted attribute values that cannot break out. Hostile
// input survives only as escaped text, never as an element or attribute.
const ALLOWED_TAG =
  /<\/?(html|head|meta|title|style|body|p|h[1-3]|ul|ol|li|pre|code|hr|br|a|strong|em|span|div|svg|g|defs|marker|path|rect|line|circle|text)( +[a-zA-Z][a-zA-Z0-9-]*="[^"<>]*")* *\/?>/;
function assertTagsAllowlisted(html: string): void {
  const tags = (html.match(/<[^<>]+>/g) ?? []).filter((tag) => !tag.startsWith("<!"));
  expect(tags.length).toBeGreaterThan(0);
  for (const tag of tags) {
    expect(tag, `non-allowlisted tag: ${tag}`).toMatch(ALLOWED_TAG);
  }
}

describe("text renderers", () => {
  it("escapes every HTML-significant character", () => {
    expect(escapeHtml(`&<>"'`)).toBe("&amp;&lt;&gt;&quot;&#39;");
  });

  it("renders the markdown subset and keeps hostile markup inert", () => {
    const { html } = renderMarkdownToHtml(
      `# Title\n\nHello **bold** and *em* with \`code\`.\n\n[ok](https://bfb.example.test/x?a=1)\n\n${HOSTILE_SCRIPT}\n${HOSTILE_IMG}\n\n[evil](javascript:alert(1))\n\n![alt text](https://evil.example.test/x.png)\n\n- one\n- two\n\n1. first\n\n\`\`\`\n<script>code fence</script>\n\`\`\`\n`,
    );
    expect(html).toContain("<h1>Title</h1>");
    expect(html).toContain("<strong>bold</strong>");
    expect(html).toContain("<em>em</em>");
    expect(html).toContain("<code>code</code>");
    expect(html).toContain('<a href="https://bfb.example.test/x?a=1" rel="noopener">ok</a>');
    expect(html).toContain("<ul>");
    expect(html).toContain("<ol>");
    // The javascript: target stays unlinked visible text; only href creation would be active.
    expect(html).not.toContain("href=\"javascript");
    expect(html).toContain("[evil](javascript:alert(1))");
    expect(html).toContain("&lt;script&gt;");
    expect(html).toContain("&lt;img src=x onerror=alert(1)&gt;");
    expect(html).toContain("alt text");
    assertTagsAllowlisted(html);
  });

  it("renders strict mermaid flowcharts without links, scripts, or foreign content", () => {
    const rendered = renderMermaidToSvg(
      `graph TD\nA[Start]-->B{Decide}\nB-->|yes|C((Done))\nB---|no|A\n`,
    );
    expect(rendered.kind).toBe("svg");
    if (rendered.kind !== "svg") throw new Error("expected svg");
    expect(rendered.svg).toContain("<svg");
    expect(rendered.svg).toContain("Start");
    expect(rendered.dropped).toBe(0);
    expect(rendered.svg).not.toContain("foreignObject");
    assertTagsAllowlisted(rendered.svg);
  });

  it("drops active mermaid directives and counts them", () => {
    const rendered = renderMermaidToSvg(
      `graph TD\nA-->B\nclick A javascript:alert(1)\nstyle A fill:red\nclassDef bad fill:blue\nB-->C\n`,
    );
    expect(rendered.kind).toBe("svg");
    if (rendered.kind !== "svg") throw new Error("expected svg");
    expect(rendered.dropped).toBe(3);
    expect(rendered.svg).toContain("omitted");
    assertTagsAllowlisted(rendered.svg);
  });

  it("falls back safely past graph caps or without a graph line", () => {
    const edges = Array.from({ length: VIEWER_MAX_MERMAID_EDGES + 1 }, (_, index) => `N${index}-->M${index}`);
    const over = renderMermaidToSvg(`graph TD\n${edges.join("\n")}\n`);
    expect(over.kind).toBe("fallback");
    const nodes = Array.from({ length: VIEWER_MAX_MERMAID_NODES + 1 }, (_, index) => `N${index}`);
    const overNodes = renderMermaidToSvg(`graph TD\n${nodes.join("\n")}\n`);
    expect(overNodes.kind).toBe("fallback");
    expect(renderMermaidToSvg(`A-->B\n`).kind).toBe("fallback");
    const fallback = buildViewerFallback("over_graph_cap");
    expect(fallback).toContain("Preview unavailable");
    expect(fallback).not.toMatch(/<script/i);
  });

  it("drops mermaid labels carrying markup instead of rendering them", () => {
    const rendered = renderMermaidToSvg(`graph TD\nA[${HOSTILE_SCRIPT}]-->B\nA-->B\n`);
    expect(rendered.kind).toBe("svg");
    if (rendered.kind !== "svg") throw new Error("expected svg");
    expect(rendered.dropped).toBe(1);
    expect(rendered.svg).toContain("omitted");
    expect(rendered.svg).not.toContain("alert(");
    assertTagsAllowlisted(rendered.svg);
    const benign = renderMermaidToSvg(`graph TD\nA[Plain label 123]-->B\n`);
    expect(benign.kind).toBe("svg");
    if (benign.kind !== "svg") throw new Error("expected svg");
    expect(benign.svg).toContain("Plain label 123");
  });

  it("highlights diffs and truncates over-long input", () => {
    const { html, truncated } = renderDiffToHtml(
      `diff --git a/x b/x\n--- a/x\n+++ b/x\n@@ -1 +1 @@\n-${HOSTILE_SCRIPT}\n+safe\n context\n`,
    );
    expect(truncated).toBe(false);
    expect(html).toContain('class="add"');
    expect(html).toContain('class="del"');
    expect(html).toContain('class="hunk"');
    expect(html).toContain('class="meta"');
    expect(html).not.toMatch(/<script[\s>]/i);
    const big = renderDiffToHtml(Array.from({ length: 10_001 }, () => "+x").join("\n"));
    expect(big.truncated).toBe(true);
    expect(big.html).toContain("first 10000 lines");
  });

  it("pretty-prints JSON and degrades invalid input to escaped text", () => {
    const { html } = renderJsonToHtml(`{"a":1,"b":[true,"<x>"]}`);
    expect(html).toContain("&quot;a&quot;");
    expect(html).not.toContain("<x>");
    const invalid = renderJsonToHtml(`{oops ${HOSTILE_SCRIPT}`);
    expect(invalid.html).toContain("Invalid JSON");
    expect(invalid.html).not.toMatch(/<script[\s>]/i);
    const nested = `[`.repeat(20_000);
    expect(renderJsonToHtml(nested).html).toContain("Invalid JSON");
  });

  it("renders logs as escaped text with line caps", () => {
    const { html, truncated } = renderLogToHtml(`line one\n${HOSTILE_SCRIPT}\nline three\n`);
    expect(truncated).toBe(false);
    expect(html).toContain("line one");
    expect(html).not.toMatch(/<script[\s>]/i);
    const big = renderLogToHtml(Array.from({ length: 10_005 }, (_, i) => `line ${i}`).join("\n"));
    expect(big.truncated).toBe(true);
  });

  it("builds deterministic script-free documents for every text format", () => {
    const hostile = `# t\n${HOSTILE_SCRIPT}\n${HOSTILE_IMG}\n`;
    for (const format of ["markdown", "mermaid", "diff", "json", "log"] as const) {
      const first = buildTextDocument(format, hostile);
      expect(buildTextDocument(format, hostile)).toBe(first);
      expect(first).not.toMatch(/<script[\s>]/i);
      expect(first).toContain("<title>Artifact preview</title>");
      assertTagsAllowlisted(first);
    }
  });

  it("renders hostile input within strict time bounds", () => {
    const markdownBomb = `${"#".repeat(3)} ${"a".repeat(200_000)}\n${"**x".repeat(50_000)}\n${"[a](https://e.test/".repeat(2000)}\n`;
    const startedMarkdown = Date.now();
    const rendered = renderMarkdownToHtml(markdownBomb);
    expect(Date.now() - startedMarkdown).toBeLessThan(2000);
    expect(rendered.html).not.toMatch(/<script/i);
    const mermaidBomb = `graph TD\n${Array.from({ length: 5000 }, (_, i) => `A${i % 50}-->B${i % 50}`).join("\n")}\n`;
    const startedMermaid = Date.now();
    expect(renderMermaidToSvg(mermaidBomb).kind).toBe("fallback");
    expect(Date.now() - startedMermaid).toBeLessThan(2000);
  });
});
