// ABOUTME: Lists the ordered F02 wire document names and schema filenames.
// ABOUTME: The generator and codec load exactly this catalog; feature packages append later.

export interface DocumentSpec {
  name: string;
  schemaFile: string;
  goType: string;
  tsType: string;
  schemaVersion?: number;
}

export const PROTOCOL_HEAD = "bfb-wire/1";
export const SCHEMA_VERSION = 1;

export const DOCUMENTS: DocumentSpec[] = [
  {
    name: "agent-update-result",
    schemaFile: "agent-update-result.json",
    goType: "AgentUpdateResult",
    tsType: "AgentUpdateResult",
  },
  {
    name: "agent-proposal-result",
    schemaFile: "agent-proposal-result.json",
    goType: "AgentProposalResult",
    tsType: "AgentProposalResult",
  },
  {
    name: "agent-effect-origin",
    schemaFile: "agent-effect-origin.json",
    goType: "AgentEffectOrigin",
    tsType: "AgentEffectOrigin",
  },
  {
    name: "local-agent-rpc",
    schemaFile: "local-agent-rpc.json",
    goType: "LocalAgentRpcEnvelope",
    tsType: "LocalAgentRpcEnvelope",
    schemaVersion: 2,
  },
  {
    name: "agent-update-request",
    schemaFile: "agent-update-request.json",
    goType: "AgentUpdateRequest",
    tsType: "AgentUpdateRequest",
  },
  {
    name: "agent-progress-request",
    schemaFile: "agent-progress-request.json",
    goType: "AgentProgressRequest",
    tsType: "AgentProgressRequest",
  },
  {
    name: "agent-proposal-request",
    schemaFile: "agent-proposal-request.json",
    goType: "AgentProposalRequest",
    tsType: "AgentProposalRequest",
  },
  {
    name: "agent-update-local-request",
    schemaFile: "agent-update-local-request.json",
    goType: "AgentUpdateLocalRequest",
    tsType: "AgentUpdateLocalRequest",
  },
  {
    name: "agent-progress-local-request",
    schemaFile: "agent-progress-local-request.json",
    goType: "AgentProgressLocalRequest",
    tsType: "AgentProgressLocalRequest",
  },
  {
    name: "agent-proposal-local-request",
    schemaFile: "agent-proposal-local-request.json",
    goType: "AgentProposalLocalRequest",
    tsType: "AgentProposalLocalRequest",
  },
  {
    name: "agent-session-reference",
    schemaFile: "agent-session-reference.json",
    goType: "AgentSessionReference",
    tsType: "AgentSessionReference",
  },
  {
    name: "agent-session-bind-request",
    schemaFile: "agent-session-bind-request.json",
    goType: "AgentSessionBindRequest",
    tsType: "AgentSessionBindRequest",
  },
  {
    name: "agent-session-bind-result",
    schemaFile: "agent-session-bind-result.json",
    goType: "AgentSessionBindResult",
    tsType: "AgentSessionBindResult",
  },
  {
    name: "agent-bound-request",
    schemaFile: "agent-bound-request.json",
    goType: "AgentBoundRequest",
    tsType: "AgentBoundRequest",
  },
  {
    name: "agent-comment-request",
    schemaFile: "agent-comment-request.json",
    goType: "AgentCommentRequest",
    tsType: "AgentCommentRequest",
  },
  {
    name: "agent-comment-result",
    schemaFile: "agent-comment-result.json",
    goType: "AgentCommentResult",
    tsType: "AgentCommentResult",
  },
  {
    name: "agent-bound-local-request",
    schemaFile: "agent-bound-local-request.json",
    goType: "AgentBoundLocalRequest",
    tsType: "AgentBoundLocalRequest",
  },
  {
    name: "agent-comment-local-request",
    schemaFile: "agent-comment-local-request.json",
    goType: "AgentCommentLocalRequest",
    tsType: "AgentCommentLocalRequest",
  },
  {
    name: "agent-work-request",
    schemaFile: "agent-work-request.json",
    goType: "AgentWorkRequest",
    tsType: "AgentWorkRequest",
  },
  {
    name: "agent-local-request",
    schemaFile: "agent-local-request.json",
    goType: "AgentLocalRequest",
    tsType: "AgentLocalRequest",
  },
  {
    name: "agent-authority-result",
    schemaFile: "agent-authority-result.json",
    goType: "AgentAuthorityResult",
    tsType: "AgentAuthorityResult",
  },
  {
    name: "agent-context-result",
    schemaFile: "agent-context-result.json",
    goType: "AgentContextResult",
    tsType: "AgentContextResult",
  },
  {
    name: "agent-task-result",
    schemaFile: "agent-task-result.json",
    goType: "AgentTaskResult",
    tsType: "AgentTaskResult",
  },
  {
    name: "event-envelope",
    schemaFile: "event-envelope.json",
    goType: "EventEnvelope",
    tsType: "EventEnvelope",
  },
  {
    name: "event-disposition",
    schemaFile: "event-disposition.json",
    goType: "EventDisposition",
    tsType: "EventDisposition",
  },
  {
    name: "runner-enrollment",
    schemaFile: "runner-enrollment.json",
    goType: "RunnerEnrollment",
    tsType: "RunnerEnrollment",
  },
  {
    name: "runner-identity",
    schemaFile: "runner-identity.json",
    goType: "RunnerIdentity",
    tsType: "RunnerIdentity",
  },
  {
    name: "runner-challenge",
    schemaFile: "runner-challenge.json",
    goType: "RunnerChallenge",
    tsType: "RunnerChallenge",
  },
  {
    name: "runner-channel-close",
    schemaFile: "runner-channel-close.json",
    goType: "RunnerChannelClose",
    tsType: "RunnerChannelClose",
  },
  {
    name: "checkout-summary",
    schemaFile: "checkout-summary.json",
    goType: "CheckoutSummary",
    tsType: "CheckoutSummary",
  },
  {
    name: "runner-local-enrollment",
    schemaFile: "runner-local-enrollment.json",
    goType: "RunnerLocalEnrollment",
    tsType: "RunnerLocalEnrollment",
  },
  {
    name: "runner-enrollment-handoff",
    schemaFile: "runner-enrollment-handoff.json",
    goType: "RunnerEnrollmentHandoff",
    tsType: "RunnerEnrollmentHandoff",
  },
  {
    name: "runner-channel-message",
    schemaFile: "runner-channel-message.json",
    goType: "RunnerChannelMessage",
    tsType: "RunnerChannelMessage",
  },
  {
    name: "runner-command-pull",
    schemaFile: "runner-command-pull.json",
    goType: "RunnerCommandPull",
    tsType: "RunnerCommandPull",
  },
  {
    name: "runner-inventory",
    schemaFile: "runner-inventory.json",
    goType: "RunnerInventory",
    tsType: "RunnerInventory",
  },
  {
    name: "execution-assignment",
    schemaFile: "execution-assignment.json",
    goType: "ExecutionAssignment",
    tsType: "ExecutionAssignment",
  },
  {
    name: "launch-specification",
    schemaFile: "launch-specification.json",
    goType: "LaunchSpecification",
    tsType: "LaunchSpecification",
  },
  {
    name: "launch-claim",
    schemaFile: "launch-claim.json",
    goType: "LaunchClaim",
    tsType: "LaunchClaim",
  },
  {
    name: "final-authorization",
    schemaFile: "final-authorization.json",
    goType: "FinalAuthorization",
    tsType: "FinalAuthorization",
  },
  {
    name: "cloud-wake-intent",
    schemaFile: "cloud-wake-intent.json",
    goType: "CloudWakeIntent",
    tsType: "CloudWakeIntent",
  },
  {
    name: "terminal-intent",
    schemaFile: "terminal-intent.json",
    goType: "TerminalIntent",
    tsType: "TerminalIntent",
  },
  {
    name: "local-rpc",
    schemaFile: "local-rpc.json",
    goType: "LocalRpcEnvelope",
    tsType: "LocalRpcEnvelope",
  },
  {
    name: "local-execution-assignment",
    schemaFile: "local-execution-assignment.json",
    goType: "LocalExecutionAssignment",
    tsType: "LocalExecutionAssignment",
  },
  {
    name: "runner-event-submission",
    schemaFile: "runner-event-submission.json",
    goType: "RunnerEventSubmission",
    tsType: "RunnerEventSubmission",
  },
  {
    name: "typed-error",
    schemaFile: "typed-error.json",
    goType: "TypedError",
    tsType: "TypedError",
  },
  {
    name: "launch-start-request",
    schemaFile: "launch-start-request.json",
    goType: "LaunchStartRequest",
    tsType: "LaunchStartRequest",
  },
  {
    name: "launch-snapshot",
    schemaFile: "launch-snapshot.json",
    goType: "LaunchSnapshot",
    tsType: "LaunchSnapshot",
  },
  {
    name: "launch-claim-result",
    schemaFile: "launch-claim-result.json",
    goType: "LaunchClaimResult",
    tsType: "LaunchClaimResult",
  },
  {
    name: "launch-final-request",
    schemaFile: "launch-final-request.json",
    goType: "LaunchFinalRequest",
    tsType: "LaunchFinalRequest",
  },
  {
    name: "launch-reconciliation",
    schemaFile: "launch-reconciliation.json",
    goType: "LaunchReconciliation",
    tsType: "LaunchReconciliation",
  },
  {
    name: "checkout-lease-observation",
    schemaFile: "checkout-lease-observation.json",
    goType: "CheckoutLeaseObservation",
    tsType: "CheckoutLeaseObservation",
  },
  {
    name: "run-control-request",
    schemaFile: "run-control-request.json",
    goType: "RunControlRequest",
    tsType: "RunControlRequest",
  },
  {
    name: "run-control-claim",
    schemaFile: "run-control-claim.json",
    goType: "RunControlClaim",
    tsType: "RunControlClaim",
  },
  {
    name: "run-control-disposition",
    schemaFile: "run-control-disposition.json",
    goType: "RunControlDisposition",
    tsType: "RunControlDisposition",
  },
  {
    name: "launch-reject-request",
    schemaFile: "launch-reject-request.json",
    goType: "LaunchRejectRequest",
    tsType: "LaunchRejectRequest",
  },
  {
    name: "launch-tighten-request",
    schemaFile: "launch-tighten-request.json",
    goType: "LaunchTightenRequest",
    tsType: "LaunchTightenRequest",
  },
  {
    name: "launch-wake-request",
    schemaFile: "launch-wake-request.json",
    goType: "LaunchWakeRequest",
    tsType: "LaunchWakeRequest",
  },
  {
    name: "launch-wake-redemption",
    schemaFile: "launch-wake-redemption.json",
    goType: "LaunchWakeRedemption",
    tsType: "LaunchWakeRedemption",
  },
  {
    name: "run-control-reference",
    schemaFile: "run-control-reference.json",
    goType: "RunControlReference",
    tsType: "RunControlReference",
  },
  {
    name: "run-control-result",
    schemaFile: "run-control-result.json",
    goType: "RunControlResult",
    tsType: "RunControlResult",
  },
  {
    name: "local-execution-observation",
    schemaFile: "local-execution-observation.json",
    goType: "LocalExecutionObservation",
    tsType: "LocalExecutionObservation",
  },
  {
    name: "local-execution-control",
    schemaFile: "local-execution-control.json",
    goType: "LocalExecutionControl",
    tsType: "LocalExecutionControl",
  },
  {
    name: "local-execution-focus",
    schemaFile: "local-execution-focus.json",
    goType: "LocalExecutionFocus",
    tsType: "LocalExecutionFocus",
  },
  {
    name: "discussion-create-request",
    schemaFile: "discussion-create-request.json",
    goType: "DiscussionCreateRequest",
    tsType: "DiscussionCreateRequest",
  },
  {
    name: "discussion-change-request",
    schemaFile: "discussion-change-request.json",
    goType: "DiscussionChangeRequest",
    tsType: "DiscussionChangeRequest",
  },
  {
    name: "discussion-turn-request",
    schemaFile: "discussion-turn-request.json",
    goType: "DiscussionTurnRequest",
    tsType: "DiscussionTurnRequest",
  },
  {
    name: "discussion-recommendation",
    schemaFile: "discussion-recommendation.json",
    goType: "DiscussionRecommendation",
    tsType: "DiscussionRecommendation",
  },
  {
    name: "discussion-receipt",
    schemaFile: "discussion-receipt.json",
    goType: "DiscussionReceipt",
    tsType: "DiscussionReceipt",
  },
  {
    name: "discussion-view",
    schemaFile: "discussion-view.json",
    goType: "DiscussionView",
    tsType: "DiscussionView",
  },
  {
    name: "agent-capture-confirmation-request",
    schemaFile: "agent-capture-confirmation-request.json",
    goType: "AgentCaptureConfirmationRequest",
    tsType: "AgentCaptureConfirmationRequest",
  },
  {
    name: "agent-capture-confirmation-result",
    schemaFile: "agent-capture-confirmation-result.json",
    goType: "AgentCaptureConfirmationResult",
    tsType: "AgentCaptureConfirmationResult",
  },
  {
    name: "agent-work-capture",
    schemaFile: "agent-work-capture.json",
    goType: "AgentWorkCapture",
    tsType: "AgentWorkCapture",
  },
  {
    name: "agent-work-replay-request",
    schemaFile: "agent-work-replay-request.json",
    goType: "AgentWorkReplayRequest",
    tsType: "AgentWorkReplayRequest",
  },
  {
    name: "agent-work-receipt",
    schemaFile: "agent-work-receipt.json",
    goType: "AgentWorkReceipt",
    tsType: "AgentWorkReceipt",
  },
  {
    name: "local-agent-work-rpc",
    schemaFile: "local-agent-work-rpc.json",
    schemaVersion: 3,
    goType: "LocalAgentWorkRpcEnvelope",
    tsType: "LocalAgentWorkRpcEnvelope",
  },
];

export const SHELL_FIELDS = [
  "command",
  "executable",
  "cwd",
  "argv",
  "shell",
  "working_directory",
  "task_text",
  "task_body",
  "prompt",
] as const;
