// ABOUTME: Generates the macOS app's Codable wire models and embedded canonical schemas.
// ABOUTME: Keeps native validation deterministic and covered by the protocol drift gate.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { JsonSchema } from "./generate.js";

export async function generateSwift(
  root: string,
  registry: Map<string, JsonSchema>,
  schemaHash: string,
): Promise<void> {
  const declarations = new Map<string, string>();
  const schemas = new Map<string, JsonSchema>();
  const capitalized = (value: string) =>
    value
      .split(/[_-]/u)
      .map((part) => part[0]!.toUpperCase() + part.slice(1))
      .join("");
  const camel = (value: string) =>
    value.replace(/_([a-z])/gu, (_match, letter: string) => letter.toUpperCase());
  function type(schema: JsonSchema, owner: string, name: string): string {
    if (schema.$ref) {
      const [file, fragment] = schema.$ref.split("#");
      const target = file || owner;
      const document = registry.get(target);
      if (!document) throw new Error("Swift schema missing " + target);
      schemas.set(target, document);
      const key = fragment?.slice("/$defs/".length);
      const selected = key ? document.$defs?.[key] : document;
      if (!selected) throw new Error("Swift schema definition missing " + schema.$ref);
      return type(selected, target, key ? "Wire" + key : "Wire" + document.title);
    }
    if (schema.anyOf) {
      const nonNull = schema.anyOf.filter((item) => item.type !== "null");
      if (nonNull.length === 1 && schema.anyOf.some((item) => item.type === "null")) {
        return type(nonNull[0]!, owner, name) + "?";
      }
      throw new Error("Unsupported Swift union " + name);
    }
    if (Array.isArray(schema.type)) {
      const nonNull = schema.type.filter((item) => item !== "null");
      if (nonNull.length !== 1 || !schema.type.includes("null")) {
        throw new Error("Unsupported Swift type union " + name);
      }
      return type({ ...schema, type: nonNull[0]! }, owner, name) + "?";
    }
    switch (schema.type) {
      case "string":
        return "String";
      case "integer":
        return "Int64";
      case "boolean":
        return "Bool";
      case "array":
        return "[" + type(schema.items!, owner, name + "Item") + "]";
      case "object": {
        if (declarations.has(name)) return name;
        declarations.set(name, "");
        const required = new Set(schema.required ?? []);
        const fields = Object.entries(schema.properties ?? {}).map(([key, value]) => {
          const fieldType = type(value, owner, name + capitalized(key));
          const optional = !required.has(key) || fieldType.endsWith("?");
          return { key, fieldType, optional };
        });
        const lines = fields.map(
          ({ key, fieldType, optional }) =>
            "  var " +
            camel(key) +
            ": " +
            fieldType.replace(/\?$/u, "") +
            (optional ? "? = nil" : ""),
        );
        lines.push("", "  enum CodingKeys: String, CodingKey {");
        for (const { key } of fields)
          lines.push(
            "    case " + camel(key) + (camel(key) === key ? "" : " = " + JSON.stringify(key)),
          );
        lines.push("  }");
        if (fields.some(({ key, optional }) => required.has(key) && optional)) {
          lines.push(
            "",
            "  func encode(to encoder: Encoder) throws {",
            "    var container = encoder.container(keyedBy: CodingKeys.self)",
          );
          for (const { key } of fields)
            lines.push(
              "    try container." +
                (required.has(key) ? "encode" : "encodeIfPresent") +
                "(" +
                camel(key) +
                ", forKey: ." +
                camel(key) +
                ")",
            );
          lines.push("  }");
        }
        declarations.set(
          name,
          "struct " + name + ": Codable, Sendable {\n" + lines.join("\n") + "\n}",
        );
        return name;
      }
      default:
        throw new Error("Unsupported Swift schema " + name);
    }
  }
  type({ $ref: "local-rpc.json" }, "local-rpc.json", "WireLocalRpcEnvelope");
  const embedded = JSON.stringify(Object.fromEntries(schemas));
  const lines = [
    "// ABOUTME: Defines generated Codable models for the bounded Local RPC contract.",
    "// ABOUTME: Embeds canonical schemas used by the app's strict native decoder.",
    "// Code generated by tools/protocol. DO NOT EDIT.",
    "// Schema hash: " + schemaHash,
    "",
    "import Foundation",
    "",
    ...Array.from(declarations.values()).flatMap((value) => [value, ""]),
    "enum WireSchemas {",
    '  static let json = #"""',
    "    " + embedded,
    '    """#',
    "}",
    "",
  ];
  const directory = path.join(root, "apps/macos/Sources/BFB");
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, "WireGenerated.swift"), lines.join("\n"));
}
