// ABOUTME: Generates deterministic provider aggregation from provider-owned registration files.
// ABOUTME: Checks drift so adding a provider never requires hand-editing a shared command or registry.

import { spawnSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const check = process.argv[2] === "--check";
if (process.argv.length > (check ? 3 : 2)) throw new Error("Usage: generate.mjs [--check]");
const root = "internal/providers";
const names = readdirSync(root, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => {
    const registration = JSON.parse(
      readFileSync(path.join(root, entry.name, "registration.json"), "utf8"),
    );
    if (
      !/^[a-z][a-z0-9]*$/u.test(entry.name) ||
      registration.name !== entry.name ||
      Object.keys(registration).join() !== "name"
    )
      throw new Error("Invalid provider-owned registration");
    return entry.name;
  })
  .sort();
const source = [
  "// ABOUTME: Aggregates compiled provider-local descriptors in deterministic name order.",
  "// ABOUTME: Generated by pnpm provider:generate; provider packages own their registration files.",
  "",
  "package providers",
  "",
  'import ("github.com/qdis/bfb/internal/provider"',
  ...names.map((name) => '"github.com/qdis/bfb/internal/providers/' + name + '"'),
  ")",
  "",
  "func Descriptors() []provider.Descriptor { return []provider.Descriptor{",
  ...names.map((name) => name + ".Descriptor(),"),
  "} }",
  "",
].join("\n");
const formatted = spawnSync("gofmt", [], { input: source, encoding: "utf8" });
if (formatted.status !== 0) throw new Error("Provider registry formatting failed");
const target = path.join(root, "catalog.generated.go");
if (check) {
  if (readFileSync(target, "utf8") !== formatted.stdout)
    throw new Error("Provider registry drift; run pnpm provider:generate");
} else writeFileSync(target, formatted.stdout);
