// ABOUTME: Aggregates compiled provider-local descriptors in deterministic name order.
// ABOUTME: Generated by pnpm provider:generate; provider packages own their registration files.

package providers

import (
	"github.com/qdis/bfb/internal/provider"
	"github.com/qdis/bfb/internal/providers/claude"
	"github.com/qdis/bfb/internal/providers/codex"
	"github.com/qdis/bfb/internal/providers/fake"
	"github.com/qdis/bfb/internal/providers/grok"
)

func Descriptors() []provider.Descriptor {
	return []provider.Descriptor{
		claude.Descriptor(),
		codex.Descriptor(),
		fake.Descriptor(),
		grok.Descriptor(),
	}
}
